
options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/taxgpt-backend-image:$SHORT_SHA', '.']
  id: Creating a new image
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'taxgpt-backend', '--image', 'gcr.io/$PROJECT_ID/taxgpt-backend-image:$SHORT_SHA',
    '--region', 'us-central1', '--platform', 'managed', 
    '--update-secrets=OPENAI_API_KEY=openai-api-key:latest',
    '--memory', '1Gi',
    '--cpu', '2',
    '--concurrency', '80',
    '--timeout', '30',
    '--min-instances', '1',
    '--max-instances', '10',
    ]
  id: Deploying Cloud Run
timeout: '1600s'
